export const questionTypes = [
  {
    value: "BASICS",
    label: "Basics",
    enabled: true,
  },
  {
    value: "FAVORITES",
    label: "Hobbies and Favorite Things",
    enabled: true,
  },
  {
    value: "EXPERIENCES",
    label: "Life Experiences",
    enabled: true,
  },
  {
    value: "SOCIAL_MEDIA",
    label: "Social Media",
    enabled: true,
  },
  {
    value: "PERSONAL_BELONGINGS",
    label: "Personal Belongings",
    enabled: true,
  },
  {
    value: "LOOKS",
    label: "Looks and Appearances",
    enabled: true,
  },
  {
    value: "RELATIONSHIPS",
    label: "Relationships",
    enabled: true,
  },
  {
    value: "NSFW",
    label: "Sex, Sexual, and Sexuality (NSFW Stuff)",
    enabled: true,
  },
  {
    value: "ACADEMICS",
    label: "Academics and School",
    enabled: true,
  },
  {
    value: "ECONOMIC_STATUS",
    label: "Economic Status or Wealth",
    enabled: true,
  },
  {
    value: "MISC",
    label: "Miscellaneous",
    enabled: true,
  }
];

//THE NUMBERS GAME BY u/German-Spy
export const questions = {
  BASICS: [
    "Age",
    "Gender",
    "Height",
    "Weight",
    "Where are you from",
    "Zodiac Sign",
    "First Name",
    "Last Name",
    "Middle Name",
    "Birthday",
    "Main Language(s)"
  ],
  FAVORITES: [
    "Favorite Color",
    "Favorite Food",
    "Favorite Activity",
    "Favorite Music genre",
    "Favorite Artist",
    "Favorite Song",
    "Favorite Movie",
    "Favorite Video Game (if any)",
    "Favorite TV show",
    "Do you play any sports",
    "Last thing you did"
  ],
  EXPERIENCES: [
    "Do you currently have a job",
    "Future Job/Career/Ambitions",
    "Have you drank/smoked anything",
    "Have you done drugs",
    "Do you have any pets",
    "Most Favorable Memory",
    "Most embarrassing moment",
    "Dream Vacation",
    "How many Family members",
    "How many friends",
    "Do you plan on going to college/university"
  ],
  SOCIAL_MEDIA: [
    "Do you use any other social media then Reddit",
    "Who do you follow",
    "Have you ever had an internet argument",
    "Most used Social Media app",
    "What's your username on each app",
    "Have you met any friends online",
    "Do you follow any NSFW accounts/pages",
    "Last Person you DM'd/followed",
    "What was the last message you sent",
    "How many followers/friends on social media",
    "Amount of time you use social media"
  ],
  PERSONAL_BELONGINGS: [
    "Most expensive thing you own",
    "Do you own anything above $1,000",
    "Most prized possession",
    "Do you own anything embarrassing",
    "Weirdest thing you own",
    "Do you own anything popular",
    "Do you own anything considered \"rich\"",
    "Do you own anything futuristic",
    "Coolest thing you own",
    "Oldest thing you own",
    "What did you buy/get recently"
  ],
  LOOKS: [
    "Hair Style",
    "Hair Length",
    "Hair Color",
    "Body Style",
    "Ethnicity",
    "What are you wearing",
    "Eye Color",
    "Are you wearing makeup",
    "Type of Underwear you wear",
    "Favorite outfit",
    "Facial/Body Hair"
  ],
  RELATIONSHIPS: [
    "Sexuality",
    "Relationship Status",
    "Who is your crush",
    "Celebrity Crush",
    "Have you ever cheated on someone",
    "Ideal Girlfriend/Boyfriend",
    "Idea of Perfect Date",
    "Have you asked someone out",
    "What do you hope in a relationship",
    "Are you interested in anyone",
    "Do you real life/online date"
  ],
  NSFW: [
    "Have you ever seen someone naked",
    "Have you ever sucked dick",
    "Have you ever received head",
    "How often do you masturbate",
    "How do you masturbate",
    "Do you watch porn",
    "Ideal sex position",
    "Favourite sexual fantasy",
    "Has anyone seen you naked",
    "Have you ever sent a nude",
    "Have you ever received a nude",
    "Have you ever eaten pussy",
    "Have you ever eaten ass",
    "Do you like to get pegged",
    "Have you ever fingered yourself",
    "How often do you have sex",
    "Are you a dom, sub, or switch",
    "Are you into BDSM",
    "When was the last time you got hard",
    "Are you circumcised",
    "Has anyone ever caught you masturbating",
    "Most embarrassing sexual story",
    "Most horny story",
    "Do you own any sex toys",
    "What kind of porn do you watch",
    "Have you ever been fingered by someone else",
    "What makes you horny",
    "Favourite way to relieve horniness",
    "Do you use lube",
    "What kind of lube do you use ",
    "Protected or unprotected sex",
    "Have you ever been naked in public",
    "Have you ever played a strip game",
    "Do you sleep naked",
    "What kind of underwear do you wear",
    "Have you ever tasted cum",
    "Do you have any STDs",
    "Have you ever sexted before",
    "What are you wearing",
    "Are you horny",
    "Do you want to sext",
    "Are you a virgin",
    "Have you ever seen anyone naked",
    "Do you have piercing/tattoos",
    "Have you ever had same-sex expirence",
    "Have you ever sent a nude",
    "Have you ever sexted",
    "Have you ever kissed anyone",
    "Am I attractive",
    "Have you ever slept together",
    "Do you want to have sex",
    "Are you straight or part of the rainbow",
    "Bra/Dick size",
    "Pubic Hair: Natural,trimmed, shaved, none",
    "Do you have any body hair",
    "(Guys Only) Are you Circumcised",
    "How often you Masturbate",
    "Have you ever watched porn",
    "Ideal Sexual/Physical attributes",
    "Favorite Sexual Fantasy",
    "Turn Ons/Turn Offs",
    "Any Kinks",
    "Ideal Sexual Position",
    "How do you masturbate",
    "Do you own a toy",
    "Have you ever been caught Masturbating",
    "Have you ever walked in when someone was having sex",
    "Biggest fears of Sex",
    "Do you have any STDs",
    "How often are you horny",
    "Most embarrassing sexual story",
    "Are you currently horny",
    "What do you expect in a sexual relationship",
    "Are you a virgin?",
    "What turns you on the most about the opposite sex?",
    "How often would you like to have sex?",
    "Would you like to have sex in the shower?",
    "How do you masturbate?",
    "Are you easily horny?",
    "Do you have a blood penis or a flesh penis?",
    "Do you like sex with music?",
    "What is the most erogenous part of your body?",
    "What part you enjoy most in sex?",
    "What is your most recent obscene thought?",
    "Do you think scars are sexy?",
    "What type of penetration do you prefer?",
    "Are you hot?",
    "Have you ever had sex blindfolded?",
    "Have you ever masturbated until you reach an orgasm?",
    "Are you more voyeur or exhibitionist?",
    "Have you ever had sex in the water?",
    "Have you ever been attracted to a person of the same sex?",
    "Do massages turn you on?",
    "Would you like to be massaged?",
    "Where would you like to be massaged?",
    "Do you like having your hair pulled?",
    "Have you ever masturbated at work?",
    "Do you have soft or firm boobs?",
    "When was the last time you masturbated?",
    "Do you masturbate loudly or silently?",
    "What part of my body are you interested in?",
    "What are your sexual fetishes?",
    "Are you sexually satisfied in your life?",
    "Have you ever faked an orgasm?",
    "What can turn you on?",
    "If you could see through the clothes, what part of my body would you like to see?",
    "Do you like to lick?",
    "Have you ever had sex to win a bet?",
    "Have you ever been caught masturbating? ",
    "What are your favorite sexual positions?",
    "What sexual position do you like the least? ",
    "What sexual positions would you like to try?",
    "Do you like to suck?",
    "Which of my outfits excites you the most?",
    "Have you ever sent a naked photo?",
    "Have you ever received naked photos?",
    "What do you like to see in naked photos?",
    "What part of your body do you like the most?",
    "What do you think about when you masturbate?",
    "Send me a photo of my choice",
    "Send a naked photo",
    "Send me your hottest photo",
    "How sensitive are your nipples?",
    "Do you prefer sex in the evening or sex in the morning?",
    "Do you like sex toys?",
    "What sex toys have you ever tried?",
    "What sex toy would you like to try?",
    "Do you have sex toys?",
    "Do you often think about sex?",
    "What underwear are you currently wearing?",
    "How many people have you had sex with?",
    "How are your boobs/penis?",
    "How are your nipples?",
    "What do you expect from a sexual relationship?",
    "Do you like sex with or without a condom?",
    "Would you like to sleep with me?",
    "Does talking about sex make you uncomfortable?",
    "What is the size of your bra?",
    "If you were to rate me on 10, what would that rating be?",
    "Have you ever had sex outside?",
    "What is the craziest thing you have done?",
    "What kind of porn do you watch?",
    "When was the last time you watched porn?",
    "Do you often watch porn?",
    "What kind of porn have you watched recently?",
    "Do you often wake up with an erection?",
    "Have you ever bathed naked?",
    "How are your sexiest underwear?",
    "Do you sometimes look at yourself naked in the mirror?",
    "What is your highest number of masturbations in one day?",
    "Do you like the pain during sex?",
    "Do you often masturbate?",
    "What is the color of your underwear?",
    "Would you like to have sex?",
    "Do you prefer rough or sensual sex?",
    "What makes you want to masturbate?",
    "Have you ever wished you had a bigger penis/bigger boobs?",
    "Are you currently masturbating?",
    "Do you masturbate completely naked?",
    "How would you describe me in three words?",
    "Where do you prefer to ejaculate on your partners?",
    "Where do you like to receive an ejaculation?",
    "Do you think you have a pretty ass?",
    "Are you currently horny?",
    "Have you ever had sex on the floor?",
    "Do you like to sleep dressed or naked?",
    "Do you use OnlyFans, Mym, Fansly or any other similar sites?",
    "At what time of day do you like to masturbate?",
    "Do you love your body?",
    "Do you like to talk about sex?",
    "Do you prefer to masturbate in front of porn or using your imagination?",
    "Have you ever sexted?",
    "Do you like BDSM?",
    "Do you have your nipples pierced?",
    "Have you ever had sex with prostitutes?",
    "Would you go out with a prostitute?",
    "Would you consent to having a relationship with someone who does porn?",
    "Have you ever masturbated in the shower or the bath?",
    "Have you ever had sex at work?",
    "Have you ever taken a bath or shower with someone?",
    "Do you like to scratch or bite?",
    "When was the last time you had an erection?",
    "Do you like shaved or hairy genitals?",
    "Have you ever had erotic dreams?",
    "When was the last time you had an erotic dream?",
    "Do you prefer cunnilingus or anilingus?",
    "Do you prefer to spit or swallow?",
    "During sex, do you prefer the lights on or off?",
    "Have you ever slept naked?",
    "What are the physical characteristics that attract you the most?",
    "What is your favorite breast size?",
    "What is the best compliment you've ever received?",
    "Would you like to have a date with me?",
    "What type of lingerie do you find the sexiest? ",
    "Where is your most intimate tattoo/piercing? ",
    "What underwear do you prefer to wear?",
    "At what age did you first have sex?",
    "Do you think I'm fuckable?",
    "Do you masturbate to fall asleep?",
    "What is the size of your penis/boobs?",
    "Do you like to have your penis/your boobs touched?",
    "Missionary or doggy style?",
    "Have you ever read erotic books?",
    "Would you like to try a threesome?",
    "Do you like to be fingered?",
    "If you could only touch me in one place, where would it be?",
    "How often do you have sex?",
    "When was the last time you kissed someone?",
    "Where do you like to be touched?",
    "Where is your favorite place to have sex?",
    "What sexy outfit do you like to wear?",
    "Are you currently alone?",
    "Where do you usually masturbate?",
    "Have you ever played erotic games?",
    "What kind of role-playing game would excite you the most?",
    "Do you find me attractive?",
    "Are you more easily stimulated visually or mentally?",
    "How long do you masturbate continuously in one go?",
    "Where would you like to be kissed?",
    "Do you prefer to dominate or be dominated?",
    "Do you sexually fantasize about me?",
    "At what age did you start to masturbate?",
    "What are your favorite foreplay?",
    "When was the last time you had sex?",
    "Do you like to take photos of yourself completely naked?",
    "Do you like the size of your penis/breasts?",
    "What type of boobs do you prefer?",
    "Do you consider yourself sexy?",
    "Are you sometimes pervert?",
    "What kinds of accessories would you like to use during sex?",
    "How would you describe your body?",
    "Have you ever realized an erotic fantasy?",
    "Do you think you're a good kisser?",
    "Do you like to have your nipples/penis licked? ",
    "Do you prefer food before sex or sex before food? ",
    "Would you like to have a drink with me?",
    "How many sexual positions do you know?",
    "Have you ever posted naked photos publicly online? ",
    "Do you think you have nice boobs/a nice penis? ",
    "Have you ever mentally undressed someone? ",
    "Where are your underwear when you masturbate? ",
    "Have you ever had sex in a swimming pool?",
    "Do you prefer boobs or ass?",
    "Do you like morning sex?",
    "Do you like to masturbate?",
    "Have you ever had an erection and someone noticed it?",
    "Which ethnic group do you prefer?",
    "Do you have any hidden tattoos or piercings?",
  ],
  ACADEMICS: [
    "Where do you go to school",
    "What classes do you take",
    "What grade are you in",
    "Most favorite teacher",
    "Least favorite teachers",
    "Highest Grade/Lowest Grade in classes",
    "How long is your school day",
    "Did you do your homework",
    "Do you have any test, quizzes, or exams coming up",
    "Last bad grade",
    "Last good grade"
  ],
  ECONOMIC_STATUS: [
    "Are you rich/poor",
    "Where do you stand in the wealth class (lower class, middle class, upper class)",
    "How big is your house",
    "Take a picture of your house",
    "How much do your parents make",
    "Do your parents struggle with debt",
    "Do you own a pool (above-ground/below-ground)",
    "Do you live in a gated neighborhood",
    "Do you have expensive stuff",
    "How big is your room",
    "What kind of school do you go to",
  ],
  MISC: [
    "Ask me whatever you want (I can't say no)",
    "What's your mood right now",
    "What do you think of me",
    "Am I attractive",
    "Tell me to do whatever you want (I can't say no)",
    "Do you want to exchange numbers ",
    "What are you doing right now",
    "Do whatever I say (you can't say no)",
    "Do you want to date",
    "Do you want to be friends",
    "Do you want to have sex with me",
    "Send a selfie",
    "Do whatever I say (no saying no)",
    "DM me",
    "Ask whatever you want (I can't say no)"
  ]
};